version: "3.7"

services:
  breedbase:

    image: breedbase/breedbase:latest

    container_name: breedbase_cotton_web
    ports:
      - 8105:8080
    volumes:
      - type: bind
        source: /export/prod/public_cotton
        target: /home/production/volume
      - type: bind
        source: empty_db_without.test_users.sql
        target: /home/production/empty_dump.sql
      - type: bind
        source: sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - type: bind
        source: mason
        target: /home/production/cxgn/cotton/mason
      - type: bind
        source: /home/production/cotton/footer_body.mas
        target: /home/production/cxgn/sgn/mason/site/footer/body.mas
      - type: bind
        source: /home/production/cotton/analytics.mas
        target: /home/production/cxgn/cotton/mason/site/header/analytics.mas
      - type: bind
        source: db_dumps
        target: /db_dumps
      - type: bind
        source: crontab
        target: /etc/crontab
      - type: bind
        source: bash_history
        target: /root/.bash_history

volumes:
  webdata:




